version: "3.3"
services:
  sqlfsprout:
    image: mysql/mysql-server:8.0.26
    container_name: sqlsprout-backend
    restart: unless-stopped
    ports:
      - "3311:3306"
    environment:
      - MYSQL_DATABASE=sprout
      - MYSQL_USER=sprout
      - MYSQL_PASSWORD=sprout
      - MYSQL_ROOT_PASSWORD=sprout
      - MYSQL_ROOT_HOST=%
      - MYSQL_PORT=3311
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci"
  redisfanbase:
    image: redis:rc-alpine
    container_name: redissprout
    restart: unless-stopped
    ports:
      - "6969:6969"